config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'

  get 'reviews/new'

  get 'reviews/show'

  get 'reviews/create'

  devise_for :moviegoers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies do
    resources :reviews
  end
  
  root :to => redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews
    scope :for_kids, -> {where(rating: 'PG')}
end

app/models/moviegoer.rb
class Moviegoer < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :movie
    belongs_to :moviegoer
    validates :movie_id, :presence => true
    validates_associated :movie
    validates_associated :moviegoer
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate_moviegoer!
  def index
    @movies = Movie.all
  end
  def for_kids
    @movies = Movie.for_kids
  end

  def new
    #by default it will render 'new' template
  end

  def create
    @movie = Movie.create(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end
  
  def movie_params
    params.require(:movie).permit(:rating, :release_date, :title)
  end
  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfull updated"
    redirect_to movie_path(@movie)
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def show
    id = params[:id]
    @movie = Movie.find(id)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' has been deleted!"
    redirect_to movies_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_moviegoer!
  def index
    @reviews = Review.all
  end

  def new
    @movie = Movie.find_by_id(params[:movie_id])
    @review = @movie.reviews.build
  end
  def review_params
    params.require(:review).permit(:potatoes, :comments)
  end
  

  def show
  end

  def create
    @review = Review.create(review_params)
    @review.moviegoer = current_moviegoer
    @movie = Movie.find_by_id(params[:movie_id])
    @review.movie = @movie
    if @review.save
      flash[:notice] = "Review was successfully saved"
      redirect_to movie_reviews_path
    else
      flash[:notice] = "Review could not be saved"
      render 'new'
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
%body
  -if moviegoer_signed_in?
    %p Welcome. Signed in as #{current_moviegoer.email}. Not you? #{link_to 'Sign out', destroy_moviegoer_session_path, :method => :delete}
  -else
    %p.login=link_to 'Sign up', new_moviegoer_session_path
  -if flash[:notice]
    #notice.message= flash[:notice]
  -elsif flash[:warning]
    #warning.message= flash[:warning]
  = yield
  

app/views/movies/create.html.haml
%h1 Movies#create
%p Find me in app/views/movies/create.html.haml

app/views/movies/delete.html.haml
%h1 Movies#delete
%p Find me in app/views/movies/delete.html.haml

app/views/movies/edit.html.haml
%h1 Movies#edit
%p Find me in app/views/movies/edit.html.haml
= form_tag movie_path, :method => :put do
  = label :movie, :title, 'Title'
  = text_field :movie, :title
  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G', 'PG', 'PG-13', 'R', 'NC-17']
  = label :movie, :release_date, 'Released on'
  = date_select :movie, :release_date
  = submit_tag 'Save changes'

app/views/movies/index.html.haml
%h1 All Movies (Solomon)
 
%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
= link_to 'Add a new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Movies#new
%p Find me in app/views/movies/new.html.haml
%h2 Create a new Movie record
= form_tag movies_path, :method => :post do
  = label :movie, :title, 'Title'
  = text_field :movie, :title
  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G', 'PG', 'PG-13', 'R', 'NC-17']
  = label :movie, :release_date, 'Released on'
  = date_select :movie, :release_date
  = submit_tag 'Save changes'

app/views/movies/show.html.haml
%h1 Movies#show
%p Find me in app/views/movies/show.html.haml
%h2 Deatils about #{@movie.title}
%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on: 
    = @movie.release_date.strftime("%B %d, %Y")
= link_to 'Edit info', edit_movie_path(@movie)
%p
= link_to 'Add a review', new_movie_review_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
%p
= link_to 'Back to movies list', movies_path

app/views/movies/update.html.haml
%h1 Movies#update
%p Find me in app/views/movies/update.html.haml

app/views/reviews/create.html.haml
%h1 Reviews#create
%p Find me in app/views/reviews/create.html.haml

app/views/reviews/index.html.haml
%h1 All movie reviews
%table#movie_reviews
  %thead
    %tr
      %th Movie id
      %th Moviegoer id
      %th Potatoes
  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.movie_id
        %td= review.moviegoer_id
        %td= review.potatoes
        
    

app/views/reviews/new.html.haml
%h1 New review for #{@movie.title}
= form_tag movie_reviews_path(@movie) do
  %label How many potatoes:
  = select_tag 'review[potatoes]', options_for_select(1..5)
  = submit_tag 'Create review'

app/views/reviews/show.html.haml
%h1 Reviews#show
%p Find me in app/views/reviews/show.html.haml